"""proximal -> distal -> psychological/neural mapping.

The reason the cnfa.* bank matters is that each *proximal* measure (a statistic
of the light on the eye) stands for a *distal* attribute of the built
environment (something an architect can see and change), which in turn connects
to a *psychological or neural construct* (an outcome we care about). This module
holds that chain as data, so the annotation is never just a number — it carries
its interpretation and its evidence.

Each record:
  key        : the cnfa.* attribute
  proximal   : what is actually measured in the image (the light-on-the-eye)
  distal     : the environmental / architectural property it stands for
  construct  : the psychological or neural outcome it connects to
  direction  : the shape of the relationship (monotone, inverted-U, threshold)
  evidence   : short-form citation(s); full APA list in the mapping doc
  status     : "established" | "supported-with-debate" | "proxy" | "exploratory"

`status` is deliberately explicit: some links are well-replicated (fractal
preference, curvature approach), others are supported but contested (luminance
skew -> gloss), others are engineering proxies (depth -> openness). Do not
present a proxy as if it were an established causal law.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class Link:
    key: str
    proximal: str
    distal: str
    construct: str
    direction: str
    evidence: str
    status: str


PROXIMAL_DISTAL: List[Link] = [
    Link("cnfa.fractal_dimension",
         "box-counting fractal dimension D of the edge/luminance field",
         "visual richness of surfaces & silhouettes (foliage, ornament, articulation)",
         "aesthetic preference & perceived restoration",
         "inverted-U, peak D≈1.3–1.5",
         "Spehar et al. 2016; Taylor 2006; Hagerhall et al. 2004; Bies et al. 2016",
         "established"),
    Link("cnfa.fluency.spectral_slope",
         "slope of the 1/f^β radially-averaged Fourier power spectrum",
         "scene 'naturalness' vs mechanical regularity of the surface field",
         "processing fluency; naturalness judgments",
         "preference near natural β≈2 (slope≈-2)",
         "Graham & Field 2007; Redies et al. 2007; Menzel et al. 2015",
         "established"),
    Link("cnfa.fluency.radial_spectral_slope",
         "native radial power-law fit of the amplitude spectrum",
         "same as spectral_slope (independent cross-check)",
         "processing fluency; naturalness",
         "as spectral_slope",
         "Graham & Field 2007",
         "established"),
    Link("cnfa.fluency.visual_entropy_spatial",
         "first-order entropy of edge orientations",
         "organised vs disorganised visual complexity",
         "Berlyne arousal / preference; cognitive load",
         "inverted-U (some complexity preferred, too much taxes)",
         "Berlyne 1971; Van Geert & Wagemans 2020; Nadal et al. 2010",
         "established"),
    Link("cnfa.fluency.second_order_entropy",
         "second-order (pairwise) edge-orientation entropy",
         "structure/regularity of edges beyond first order",
         "perceived orderliness; fluency",
         "monotone with organisation",
         "Redies et al. 2017",
         "supported-with-debate"),
    Link("cnfa.fluency.clutter_density_count",
         "Rosenholtz Feature Congestion (colour+contrast+orientation)",
         "visual clutter of a furnished/decorated scene",
         "search cost, distraction, cognitive load",
         "monotone: more clutter -> higher load",
         "Rosenholtz et al. 2007",
         "established"),
    Link("cnfa.fluency.subband_entropy_clutter",
         "Rosenholtz Subband Entropy (encoding cost)",
         "compressibility/clutter of the scene",
         "processing load; visual comfort",
         "monotone",
         "Rosenholtz et al. 2007",
         "established"),
    Link("cnfa.fluency.symmetry_score_horizontal",
         "Redies QIP mirror-symmetry index",
         "façade/interior bilateral symmetry",
         "processing fluency, beauty, prototypicality",
         "monotone (more symmetry -> more fluent), context-dependent",
         "Tinio & Leder 2009; Reber et al. 2004",
         "supported-with-debate"),
    Link("cnfa.fluency.symmetry_lr_corr",
         "left-right luminance mirror correlation",
         "bilateral symmetry of the view",
         "fluency / beauty",
         "monotone",
         "Reber et al. 2004",
         "supported-with-debate"),
    Link("cnfa.fluency.self_similarity",
         "PHOG self-similarity across pyramid levels",
         "hierarchical order of ornament/pattern",
         "artistic order; preference",
         "higher self-similarity in preferred/‘artful’ images",
         "Redies et al. 2012; Braun et al. 2013",
         "supported-with-debate"),
    Link("cnfa.fluency.hierarchy_depth",
         "PHOG complexity (pyramid HOG)",
         "amount of structured detail across scales",
         "complexity arm of the Berlyne preference function",
         "inverted-U",
         "Berlyne 1971; Redies 2015",
         "supported-with-debate"),
    Link("cnfa.fluency.anisotropy",
         "PHOG anisotropy of gradient strength across orientations",
         "directional bias of structure (striped vs isotropic)",
         "order/complexity perception",
         "context-dependent",
         "Redies et al. 2017",
         "exploratory"),
    Link("cnfa.fluency.colorfulness",
         "Hasler-Susstrunk opponent-channel colourfulness",
         "chromatic vividness of the palette",
         "arousal, positive affect, preference",
         "inverted-U / context-dependent",
         "Hasler & Susstrunk 2003; Palmer & Schloss 2010",
         "supported-with-debate"),
    Link("cnfa.fluency.color_palette_entropy",
         "Shannon entropy of the colour channels",
         "palette variety (monochrome vs varied)",
         "arousal; visual interest",
         "inverted-U",
         "Palmer & Schloss 2010",
         "exploratory"),
    Link("cnfa.fluency.figure_ground_clarity",
         "concentration (1 - normalised entropy) of the saliency map",
         "how cleanly one region reads as figure",
         "processing fluency; ease of orienting",
         "monotone",
         "Rosenholtz; Kümmerer et al. 2017",
         "proxy"),
    Link("cnfa.light.warm_vs_cool_ratio",
         "correlated colour temperature (CCT) from mean chromaticity",
         "warm vs cool lighting/finish of the space",
         "arousal, comfort, perceived cosiness/alertness",
         "warmer -> relaxation; cooler -> alertness (context/task-dependent)",
         "Vartanian et al. 2013; Küller et al. 2006",
         "supported-with-debate"),
    Link("cnfa.light.luminance_mean",
         "mean relative luminance",
         "overall brightness of the scene",
         "alertness, mood, perceived spaciousness",
         "monotone within range",
         "Küller et al. 2006",
         "established"),
    Link("cnfa.light.rms_contrast",
         "RMS luminance contrast",
         "contrast/drama of the lighting",
         "visual salience, arousal",
         "monotone within range",
         "Peli 1990",
         "established"),
    Link("cnfa.material.luminance_skew",
         "skewness of the luminance histogram",
         "surface gloss / specularity of materials",
         "perceived glossiness (a material-quality percept)",
         "positive skew -> glossier (with caveats)",
         "Motoyoshi et al. 2007; Kim & Anderson 2010 (counter)",
         "supported-with-debate"),
    Link("cnfa.material.subband_skew",
         "skewness of the high-pass (sub-band) luminance",
         "specular highlights independent of albedo",
         "perceived gloss (stronger predictor than raw skew)",
         "positive -> glossier",
         "Motoyoshi et al. 2007",
         "supported-with-debate"),
    Link("cnfa.material.perceived_gloss",
         "learned perceived-gloss model output (research worker)",
         "material glossiness as humans rate it",
         "material-quality percept; luxury/hardness reading",
         "monotone",
         "Guerrero-Viu et al. 2024; Storrs et al. 2021",
         "exploratory"),
    Link("cnfa.haptic.texture_variation_index",
         "GLCM contrast",
         "surface roughness/relief of materials",
         "perceived roughness; tactile expectation; visual interest",
         "monotone",
         "Haralick et al. 1973; Bhushan et al. 1997",
         "established"),
    Link("cnfa.haptic.haralick_entropy",
         "Haralick texture entropy",
         "textural disorder of surfaces",
         "perceived complexity/naturalness of material",
         "monotone",
         "Haralick et al. 1973",
         "established"),
    Link("cnfa.haptic.lbp_entropy",
         "Local Binary Pattern histogram entropy",
         "micro-texture richness of surfaces",
         "material naturalness; visual interest",
         "monotone",
         "Ojala et al. 2002",
         "proxy"),
    Link("cnfa.geometry.curvilinearity",
         "mean |shape index| of local surface curvature",
         "curved vs rectilinear forms in the space",
         "approach vs avoidance; beauty",
         "curved -> approach/beauty; sharp -> threat/avoidance",
         "Bar & Neta 2006; Vartanian et al. 2013; Corradi & Munar 2020",
         "established"),
    Link("cnfa.geometry.straight_edge_ratio",
         "fraction of edge pixels on detected straight lines",
         "rectilinearity of the architecture (grids vs curves)",
         "approach/avoidance; perceived order",
         "inverse of curvilinearity effect",
         "Vartanian et al. 2013",
         "supported-with-debate"),
    Link("cnfa.geometry.zernike_magnitude",
         "norm of Zernike shape moments",
         "rotation-invariant shape complexity of forms",
         "form complexity perception",
         "monotone with complexity",
         "Khotanzad & Hong 1990",
         "exploratory"),
    Link("cnfa.dynamic.depth_of_field",
         "blur_effect (global blur estimate)",
         "focal depth cueing / photographic depth of field",
         "focal guidance of attention; perceived depth",
         "monotone (more blur -> stronger focal cue)",
         "Crete et al. 2007",
         "proxy"),
    Link("cnfa.spatial.isovist_openness",
         "far-field fraction of the recovered depth map (or isovist area)",
         "openness / prospect of the space",
         "prospect; exploration; perceived spaciousness",
         "monotone with openness",
         "Benedikt 1979; Stamps 2005",
         "proxy"),
    Link("cnfa.spatial.enclosure_index",
         "near-field fraction of the depth map (or occluding solid angle)",
         "enclosure / refuge of the space",
         "refuge; safety; intimacy",
         "monotone with enclosure",
         "Appleton 1975; Stamps 2005",
         "proxy"),
    Link("cnfa.spatial.prospect_to_refuge_ratio",
         "ratio of far to near depth (or prospect/refuge isovist areas)",
         "balance of outlook vs shelter",
         "environmental preference (prospect-refuge)",
         "moderate ratio preferred; extremes penalised",
         "Appleton 1975; Dosen & Ostwald 2016 (meta-analysis)",
         "supported-with-debate"),
    Link("cnfa.biophilic.natural_material_ratio",
         "segmented area fraction of natural materials/elements",
         "biophilic material presence (wood, stone, water, plants)",
         "restoration; stress reduction; positive affect",
         "monotone (more natural -> more restorative)",
         "Ulrich 1984; Kaplan 1995; Demattè et al. 2018",
         "established"),
    Link("cnfa.biophilic.greenery_ratio",
         "segmented vegetation area fraction",
         "visible greenery / planting",
         "attention restoration; stress reduction",
         "monotone",
         "Kaplan & Kaplan 1989; Berman et al. 2008",
         "established"),
    Link("cnfa.cognitive.landmark_salience",
         "peak of the saliency/fixation-density map",
         "presence of a dominating focal element",
         "landmark legibility; wayfinding anchoring",
         "monotone",
         "Itti & Koch 2000; Kümmerer et al. 2017",
         "proxy"),
    Link("cnfa.cognitive.memorability",
         "learned memorability score (ResMem/ViTMem)",
         "how memorable the space is (intrinsic image property)",
         "recognition memory; place identity / wayfinding",
         "monotone",
         "Isola et al. 2011; Needell & Bainbridge 2022; Hagen & Espeseth 2023",
         "established"),
    Link("cnfa.cognitive.activity_zones_count",
         "count of segmented distinct regions/zones",
         "programmatic differentiation of the space",
         "legibility; behavioural affordance variety",
         "context-dependent",
         "Gibson 1979 (affordances)",
         "exploratory"),
    Link("cnfa.color.hue_entropy",
         "saturation-weighted entropy of the hue histogram",
         "palette variety of the space",
         "arousal; visual interest",
         "inverted-U",
         "Palmer & Schloss 2010",
         "exploratory"),
    Link("cnfa.color.opponent_rg_mean",
         "mean CIELab a* (red-green opponent channel)",
         "warm-red vs cool-green cast of surfaces/light",
         "colour affect (LGN-encoded)",
         "context-dependent",
         "Palmer & Schloss 2010; Hurvich & Jameson 1957",
         "exploratory"),
    Link("cnfa.evaluation.aesthetic_score",
         "learned NIMA/MUSIQ aesthetic score (validation only)",
         "generic photographic 'beauty' (not a cognitive-code metric)",
         "an external signal to validate the causal bank against",
         "validation cross-check",
         "Talebi & Milanfar 2018",
         "proxy"),
    # --- operators_v2 flagship (Codex) -------------------------------------
    Link("cnfa.contour.curvilinear_ratio",
         "fraction of edge-contour length that is smoothly curved",
         "curved vs angular forms in the space",
         "approach vs avoidance; beauty; rest vs stress",
         "curved -> approach/rest; angular -> avoidance/stress",
         "Bar & Neta 2006; Vartanian et al. 2013; Frontiers contour study 2022",
         "established"),
    Link("cnfa.salience.attention_concentration",
         "1 - normalised entropy of a (spectral-residual) saliency map",
         "presence of a dominating focal element / visual hierarchy",
         "attention capture; fascination (soft vs hard)",
         "monotone; too high may reduce fascination",
         "Hou & Zhang 2007; Berto 2005 (fascination)",
         "proxy"),
    Link("cnfa.biophilic.green_view_ratio",
         "Excess-Green (ExG) vegetation-index pixel fraction",
         "visible greenery / green view index",
         "restoration; stress reduction (visible nature exposure)",
         "monotone (exposure, not a health claim)",
         "Kaplan & Kaplan 1989; Berman et al. 2008; green-view-index literature",
         "supported-with-debate"),
    Link("cnfa.spatial.depth_openness_index",
         "mean normalised monocular depth",
         "openness / spaciousness of the view",
         "prospect; perceived spaciousness",
         "monotone with openness",
         "Stamps 2005; Franz & Wiener 2008",
         "proxy"),
    # --- isovist / visibility-graph (space-side) ---------------------------
    Link("cnfa.spatial.isovist_area",
         "visible floor area from the viewpoint (ray-cast isovist)",
         "openness / prospect of the standpoint",
         "prospect, perceived spaciousness, exploration",
         "monotone with openness",
         "Benedikt 1979; Stamps 2005; Franz & Wiener 2008",
         "established"),
    Link("cnfa.spatial.isovist_occlusivity",
         "length of the occluding (radial) isovist edges",
         "hidden space — how much is 'around the corner'",
         "mystery; information rate; exploratory drive",
         "monotone with mystery",
         "Benedikt 1979; Kaplan 1987; Wiener et al. 2007",
         "supported-with-debate"),
    Link("cnfa.spatial.isovist_jaggedness",
         "isovist perimeter^2 / area (boundary complexity)",
         "spatial complexity of the visible field",
         "mystery and preference (Kaplan)",
         "inverted-U / context-dependent",
         "Kaplan 1987; Franz & Wiener 2008",
         "supported-with-debate"),
    Link("cnfa.spatial.isovist_drift",
         "distance from viewpoint to isovist centroid (+ direction)",
         "asymmetry of outlook — the pull toward open space",
         "anticipated movement direction; exploration",
         "monotone; direction predicts movement",
         "Wiener et al. 2007; Franz & Wiener 2008",
         "supported-with-debate"),
    Link("cnfa.topology.integration_value",
         "visibility-graph integration (Hillier) at the standpoint",
         "how central vs segregated the standpoint is in the visual network",
         "wayfinding legibility; predicted movement & co-presence",
         "monotone: more integrated -> more used / easier to find",
         "Hillier & Hanson 1984; Turner et al. 2001",
         "established"),
    Link("cnfa.topology.intelligibility",
         "R^2 between local connectivity and global integration",
         "how well the local view predicts the whole layout",
         "global wayfinding legibility of the plan",
         "monotone",
         "Hillier 1996; Turner et al. 2001",
         "established"),
    # --- prospect / refuge / privacy / dead-ground (corrected) -------------
    Link("cnfa.spatial.prospect_depth",
         "maximum sightline length from the standpoint (warning depth)",
         "how far you can see an approach coming",
         "prospect (threat warning) + orientation/legibility",
         "monotone: farther sight -> more warning",
         "Appleton 1975; Gibson 1979; Fisher & Nasar 1992",
         "supported-with-debate"),
    Link("cnfa.spatial.refuge_enclosure",
         "solid-boundary fraction of the isovist",
         "how enclosed / back-protected the standpoint is",
         "refuge; felt security",
         "monotone with enclosure (to a point)",
         "Appleton 1975; Stamps 2005",
         "supported-with-debate"),
    Link("cnfa.spatial.dead_ground_ratio",
         "near-field free space NOT visible from the standpoint",
         "covert-approach lanes / offender concealment near you",
         "vulnerability; fear of crime",
         "monotone: more dead ground -> more fear/risk",
         "Fisher & Nasar 1992; Nasar, Fisher & Grannis 1993",
         "established"),
    Link("cnfa.spatial.first_detection_distance",
         "range at which a min-exposure approach is first seen",
         "quality of surveillance over the approach",
         "felt security; ambush risk",
         "monotone: seen from farther -> safer",
         "Marzouqi & Jarvis 2011; Fisher & Nasar 1992",
         "supported-with-debate"),
    Link("cnfa.spatial.visual_exposure",
         "fraction of the public set with line of sight to the standpoint",
         "how exposed the standpoint is to public/circulation space",
         "privacy (inverse); surveillance",
         "monotone; privacy_index = 1 - exposure",
         "Fisher-Gewirtzman & Wagner 2003; Newman 1972",
         "established"),
    Link("cnfa.social.covisibility_potential",
         "integration-weighted visible area (used space you can see)",
         "opportunity to see and be joined by others",
         "co-presence; informal social interaction",
         "monotone with integrated visible space",
         "Hillier & Hanson 1984; Sommer 1969",
         "supported-with-debate"),
]


def by_family() -> dict:
    fam = {}
    for l in PROXIMAL_DISTAL:
        parts = l.key.split(".")
        f = parts[1] if len(parts) > 2 else parts[-1]
        fam.setdefault(f, []).append(l)
    return fam


def to_markdown_table() -> str:
    rows = ["| cnfa key | proximal (measured) | distal (environment) | psych/neural construct | direction | status | evidence |",
            "|---|---|---|---|---|---|---|"]
    for l in PROXIMAL_DISTAL:
        rows.append("| `%s` | %s | %s | %s | %s | %s | %s |" % (
            l.key, l.proximal, l.distal, l.construct, l.direction, l.status, l.evidence))
    return "\n".join(rows)


if __name__ == "__main__":
    print(to_markdown_table())
    print("\n%d proximal->distal links." % len(PROXIMAL_DISTAL))
