factors:
  plant_presence:
    enabled: true
    weight: 0.3
    params:
      confidence_threshold: 0.5
      device: cpu
      visualize: true
      viz_dir: ../out
  natural_texture_presence:
    enabled: true
    weight: 0.7
    params:
      device: cpu
      config_path: configs/mcubes_rgbadn.yaml
      natural_labels:
        - fabric
        - sand
        - cobblestone
        - grass
        - wood
        - leaf
        - water
      visualize: true
      viz_dir: ../out
      refine_with_superpixels: true
      min_fraction: 0.05
      min_conf: 0.33
      num_superpixels: 300
      num_levels: 4
      prior: 2
      num_histogram_bins: 5
      num_iterations: 10
