"""
Wave 3 Semantics (Engine 2: The Open-Vocabulary Localizer)

This module implements the spatial grounding of the discovered taxonomy.
It takes the exhaustive vocabulary generated by Engine 1 (Taxonomy Builder) 
and feeds it into an Open-Vocabulary Segmentation pipeline (e.g. Grounding DINO + SAM) 
to generate pixel-perfect masks and bounding boxes.

Designed to run locally on Apple Silicon via PyTorch MPS backend.
"""

import json
import yaml
import os
from typing import List, Dict, Any

import torch
import cv2
import numpy as np
import urllib.request
from groundingdino.util.inference import load_model, load_image, predict
from segment_anything import sam_model_registry, SamPredictor

CANONICAL_ONTOLOGY_PATH = os.path.join(os.path.dirname(__file__), "neufert_alexander_ontology.yaml")
DYNAMIC_REGISTRY_PATH = os.path.join(os.path.dirname(__file__), "dynamic_architectural_taxonomy.json")

class Wave3Localizer:
    def __init__(self, device: str = "mps"):
        self.device = device
        print(f"[Wave3] Initializing Open-Vocabulary Segmentation models on device: {self.device}")
        self._load_models()
        self.canonical_ontology = self._load_canonical()
        self.dynamic_registry = self._load_dynamic_registry()

    def _load_models(self):
        """
        Loads Grounding DINO (bounding boxes) and SAM (segmentation masks).
        Automatically downloads open-source weights if they are not present.
        """
        weights_dir = os.path.join(os.path.dirname(__file__), "weights")
        os.makedirs(weights_dir, exist_ok=True)
        
        gdino_config = os.path.join(weights_dir, "GroundingDINO_SwinT_OGC.py")
        gdino_weights = os.path.join(weights_dir, "groundingdino_swint_ogc.pth")
        sam_weights = os.path.join(weights_dir, "sam_vit_h_4b8939.pth")

        # Basic download logic (for illustration/execution)
        if not os.path.exists(gdino_weights):
            print("[Wave3] Downloading Grounding DINO weights (this may take a moment)...")
            urllib.request.urlretrieve("https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth", gdino_weights)
        if not os.path.exists(sam_weights):
            print("[Wave3] Downloading SAM ViT-H weights (2.4GB, this will take time)...")
            urllib.request.urlretrieve("https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth", sam_weights)

        print("[Wave3] Loading Grounding DINO...")
        # Grounding DINO SwinT config is usually fetched alongside the model, assuming it's available:
        self.gdino_model = load_model(gdino_config, gdino_weights)
        
        print("[Wave3] Loading Segment Anything Model (SAM)...")
        sam = sam_model_registry["vit_h"](checkpoint=sam_weights)
        sam.to(device=self.device)
        self.sam_predictor = SamPredictor(sam)
        print(f"[Wave3] Models successfully loaded into {self.device} memory!")

    def _load_canonical(self) -> Dict[str, Any]:
        if not os.path.exists(CANONICAL_ONTOLOGY_PATH):
            return {}
        with open(CANONICAL_ONTOLOGY_PATH, 'r') as f:
            return yaml.safe_load(f)

    def _load_dynamic_registry(self) -> List[Dict[str, Any]]:
        if not os.path.exists(DYNAMIC_REGISTRY_PATH):
            return []
        with open(DYNAMIC_REGISTRY_PATH, 'r') as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return []

    def get_full_vocabulary(self) -> List[str]:
        """
        Extracts all textual search terms from both the Canonical Dictionary and the Dynamic Registry.
        """
        vocab = []
        # Extract from Canonical
        for category, items in self.canonical_ontology.get("architectural_elements", {}).items():
            for item in items:
                vocab.extend(item.get("vlm_synonyms", []))
                
        # Extract from Dynamic Registry
        for item in self.dynamic_registry:
            vocab.append(item.get("id", "").replace("_", " "))
            
        # Deduplicate and format for Grounding DINO (dot-separated)
        return list(set(vocab))

    def localize_image(self, image_path: str, specific_terms: List[str] = None) -> List[Dict[str, Any]]:
        """
        Runs Grounding DINO + SAM on the image to find the provided text terms.
        If specific_terms is None, it uses the entire vocabulary.
        """
        search_terms = specific_terms if specific_terms else self.get_full_vocabulary()
        
        # Grounding DINO requires a single text prompt separated by periods
        text_prompt = " . ".join(search_terms)
        
        print(f"[Wave3] Grounding terms in image: {image_path}")
        print(f"[Wave3] Search query length: {len(search_terms)} terms")
        
        # 1. Load Image
        image_source, image = load_image(image_path)
        
        # 2. Run Grounding DINO to get bounding boxes
        boxes, logits, phrases = predict(self.gdino_model, image, text_prompt, box_threshold=0.3, text_threshold=0.25)
        
        # 3. Run SAM on the bounding boxes to get pixel-perfect masks
        image_rgb = cv2.cvtColor(image_source, cv2.COLOR_BGR2RGB)
        self.sam_predictor.set_image(image_rgb)
        transformed_boxes = self.sam_predictor.transform.apply_boxes_torch(boxes, image_rgb.shape[:2])
        masks, _, _ = self.sam_predictor.predict_torch(point_coords=None, point_labels=None, boxes=transformed_boxes, multimask_output=False)
        
        # Assemble Results
        final_results = []
        for i, (box, phrase, logit, mask) in enumerate(zip(boxes, phrases, logits, masks)):
            final_results.append({
                "term": phrase,
                "bbox": box.tolist(),
                "confidence": float(logit),
                "mask_polygon": "POLYGON_STUB" # Real implementation would extract contour from mask
            })
        return final_results

if __name__ == "__main__":
    localizer = Wave3Localizer(device="cpu") # Mock mode
    results = localizer.localize_image("/dummy/path/to/target_office_01.jpg")
    print(f"Localized {len(results)} features. Sample result:", results[0])
