from sqlalchemy import String, Integer, Float, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing import List
from backend.database.core import Base
from backend.database.mixins import TimestampMixin

class Image(Base, TimestampMixin):
    """
    Represents the raw asset being analyzed.
    """
    __tablename__ = "images"

    id: Mapped[int] = mapped_column(primary_key=True)
    filename: Mapped[str] = mapped_column(String)
    
    # Path on disk or S3 key. 
    # v3 requirement: Do not store binary data in DB.
    storage_path: Mapped[str] = mapped_column(String)
    
    # Metadata for search (width, height, format, exif data)
    # This powers the 'Research Explorer' filters
    meta_data: Mapped[dict] = mapped_column(JSON, default={})
    
    # Tracking batch imports
    upload_batch_id: Mapped[str] = mapped_column(String, nullable=True, index=True)
    
    regions = relationship("Region", back_populates="image", cascade="all, delete-orphan")
    validations = relationship("Validation", back_populates="image")

class Region(Base, TimestampMixin):
    """
    A specific area of interest within an image (bounding box or polygon).
    Generated by SAM (Auto) or drawn by Tagger (Manual).
    """
    __tablename__ = "regions"

    id: Mapped[int] = mapped_column(primary_key=True)
    image_id: Mapped[int] = mapped_column(ForeignKey("images.id"))
    
    # Geometry: The polygon or bounding box coordinates
    # Stored as JSON to allow flexible shapes (Box vs Polygon)
    geometry: Mapped[dict] = mapped_column(JSON) 
    
    # AI Pre-label (e.g., from VLM) - The "Suggestion"
    auto_label: Mapped[str] = mapped_column(String, nullable=True)
    auto_confidence: Mapped[float] = mapped_column(Float, nullable=True)
    
    # Final Human Label - The "Ground Truth"
    manual_label: Mapped[str] = mapped_column(String, nullable=True)
    
    image = relationship("Image", back_populates="regions")