"""
Registry of feature keys that are intentionally *stubbed*.

Any key listed here is allowed to appear in the canonical feature registry
without having a concrete compute implementation yet. This file is used by
tests to ensure there are no *accidental* dangling keys.
"""

from __future__ import annotations

from typing import Set


STUB_FEATURE_KEYS: Set[str] = {
    'style.traditional',
    'style.scandinavian',
    'style.rustic',
    'style.minimalist',
    'style.mid_century_modern',
    'style.japandi',
    'style.industrial',
    'style.farmhouse',
    'style.bohemian',
    'spatial.room_function.living_room',
    'spatial.room_function.kitchen',
    'spatial.room_function.home_office',
    'spatial.room_function.bedroom',
    'spatial.room_function.bathroom',
    'affordance.L141_norm',
    'affordance.L141',
    'affordance.L130_norm',
    'affordance.L130',
    'affordance.L091_norm',
    'affordance.L091',
    'affordance.L079_norm',
    'affordance.L079',
    'affordance.L059_norm',
    'affordance.L059',
    'N/A (Computed)',
    'arch.pattern.axial_circulation_clear',
    'arch.pattern.bay_window',
    'arch.pattern.central_hearth',
    'arch.pattern.circulation_maze_like',
    'arch.pattern.colonnade',
    'arch.pattern.corner_window',
    'arch.pattern.gallery_edge',
    'arch.pattern.loft_mezzanine',
    'arch.pattern.long_view_corridor',
    'arch.pattern.perimeter_seating',
    'arch.pattern.refuge_nook',
    'arch.pattern.skylight_dominant',
    'arch.pattern.staircase_sculptural',
    'arch.pattern.threshold_emphasized',
    'arch.pattern.window_seat_niche',
    'cnfa.biophilic.natural_material_ratio',
    'cnfa.cognitive.activity_zones_count',
    'cnfa.cognitive.landmark_salience',
    'cnfa.cognitive.legibility_score',
    'cnfa.dynamic.optic_flow_magnitude',
    'cnfa.dynamic.path_glare_max',
    'cnfa.dynamic.reflection_flow',
    'cnfa.dynamic.revelation_rate',
    'cnfa.dynamic.texture_gradient',
    'cnfa.fluency.anomaly_count',
    'cnfa.fluency.clutter_density_count',
    'cnfa.fluency.figure_ground_clarity',
    'cnfa.fluency.hierarchy_depth',
    'cnfa.fluency.pattern_rhythm_regularity',
    'cnfa.fluency.visual_entropy_spatial',
    'cnfa.fluency.zoning_clarity',
    'cnfa.haptic.soft_surface_ratio',
    'cnfa.haptic.texture_variation_index',
    'cnfa.light.diffuse_vs_direct_ratio',
    'cnfa.light.vertical_illuminance_proxy',
    'cnfa.light.warm_vs_cool_ratio',
    'cnfa.spatial.ceiling_height_avg',
    'cnfa.spatial.enclosure_index',
    'cnfa.spatial.prospect_to_refuge_ratio',
    'component.bathroom.fixture.material.brass',
    'component.bathroom.fixture.material.matte_black',
    'component.bathroom.fixture.type.rain_showerhead',
    'component.ceiling.coffered',
    'component.ceiling.cove_lighting',
    'component.ceiling.exposed_beam',
    'component.ceiling.tray',
    'component.ceiling.vaulted',
    'component.kitchen.hardware.material.brass',
    'component.kitchen.hardware.material.chrome',
    'component.kitchen.hardware.material.matte_black',
    'component.kitchen.hardware.type.bar_pull',
    'component.kitchen.hardware.type.handleless',
    'component.kitchen.hardware.type.knob',
    'component.wall.material.brick_exposed',
    'component.wall.material.stone_wall',
    'component.wall.material.wood_slat',
    'component.wall.treatment.wainscoting',
    'component.wall.treatment.wallpaper_patterned',
    'provenance.architect_kengo_kuma',
    'provenance.architect_le_corbusier',
    'provenance.iconic_chair_barcelona',
    'provenance.iconic_chair_eames',
}
